baseURL = "https://blog.zkanda.io"
languageCode = "en-us"
title = "Inside My Minds Journey"
theme = "min"
DefaultContentLanguage = "en"
enableRobotsTXT = true

[author]
  name = "Zakatell Kanda"
  homepage = "https://blog.zkanda.io/"
