baseURL = "https://zkanda.io"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "intimacy of my thoughts"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "You only live once, smile and make it count."

    # Metadata for Open Graph and Twitter
    description          = "my random blabbing"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "intimacy of my thoughts"

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "about"
    text = "who is zak?"

[[params.mainMenu]]
    link = "dev"
    text = "dev"

[imaging]
    quality = 75
